---
title: "Markdown project"
author: "Christian Rubjerg Hejstvig-Larsen"
output: html_document
---

The following markdown file is for generating family data and testing the ML and REML fisher scoring algorithms.

We start by generating the family data using the functions from `generate_family_data.R`.

```{r warning=FALSE}
source("Function library/function_library.R", local = knitr::knit_global())
source("Function library/generate_family_data.R", local = knitr::knit_global())
source("ML/ml_fisher_scoring_algorithm.R", local = knitr::knit_global())
source("REML/reml_fisher_scoring_algorithm.R", local = knitr::knit_global())
```


```{r warning=FALSE}
#Define number of clusters and number of individuals in each cluster
n_clusters = 100000
n_individuals_in_cluster = 24

#Generate large dataset
#dataset <- family_dataset_generator(n_clusters = n_clusters, n_individuals_in_cluster = n_individuals_in_cluster,
#                                           n_mean_param = 1, n_variance_param = 3, mean_val = 0,
#                                           sigma_0 = 2, sigma_1 = 5, sigma_2 = 10,
#                                           seed = 1)


dataset <- dataset_generator(n_clusters = n_clusters, n_individuals_in_cluster = n_individuals_in_cluster,
                                           n_mean_param = 1, n_cov_param = 3, mean_val = 0,
                                           sigma_0 = 2, sigma_1 = 5, sigma_2 = 10,
                                           seed = 1)

#Extract relevant lists from data to run FS-algorithms
design_matrices <- dataset$design_matrices
semi_def_matrices <- dataset$semi_def_matrices
outcome <- dataset$outcome_list

get_outcome_mean(outcome = outcome)
get_outcome_variance(outcome = outcome)
```

```{r}
lower_bounds <- c(-Inf,0.000001,0.000001,0.000001)
upper_bounds <- c(Inf,Inf,Inf,Inf)

start <- Sys.time()
optim(par = c(1,1,1,1), 
      fn = log_likelihood,
      design_matrices = design_matrices, 
      semi_def_matrices = semi_def_matrices, 
      outcome_list = outcome,
      lower = lower_bounds,
      upper = upper_bounds,
      method = 'L-BFGS-B',
      control=list(fnscale=-1))
end <- Sys.time()
end - start
```



We can now run the fisher scoring algorithm

```{r}
start <- Sys.time()
mle_FS <- find_mle_parameters(init_params = c(1,1,1,1), design_matrices = design_matrices, semi_def_matrices = semi_def_matrices, outcome_list = outcome)
end <- Sys.time()
end - start
```

```{r}
mle_FS$Summary
```







